version: "3.8"
services:
  app:
    build: .
    ports:
      - 3210:3210
      - 8080:8080
    volumes:
      - ./:/app:delegated
    working_dir: /app
    tty: true
  mongodb:
    image: mongo:3.6.21-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
